// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wgnxhxygtwhoqivhylle.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndnbnhoeHlndHdob3Fpdmh5bGxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3Mjg5NTgsImV4cCI6MjA2MzMwNDk1OH0.HN-u9pBVOJEXRiS05SRjFhMa456tmSD1uWdHHDwiFzc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);